version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  db:
    image: postgress
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress