# Generated by Django 3.2.7 on 2021-09-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0002_alter_kit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
